// Mock book data
export const mockBooks = [
  {
    id: '1',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    cover: 'https://covers.openlibrary.org/b/id/7222246-L.jpg',
    description: 'A novel set in the Roaring Twenties about the mysterious Jay Gatsby.',
    genre: ['Classic', 'Fiction'],
    publishYear: 1925,
    rating: 4.2,
    pageCount: 180,
  },
  {
    id: '2',
    title: '1984',
    author: 'George Orwell',
    cover: 'https://covers.openlibrary.org/b/id/1533480-L.jpg',
    description: 'A dystopian novel exploring the dangers of totalitarianism.',
    genre: ['Dystopian', 'Science Fiction'],
    publishYear: 1949,
    rating: 4.7,
    pageCount: 328,
  },
  {
    id: '3',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    cover: 'https://covers.openlibrary.org/b/id/8226191-L.jpg',
    description: 'A profound story of racial injustice and childhood in the Deep South.',
    genre: ['Classic', 'Historical Fiction'],
    publishYear: 1960,
    rating: 4.9,
    pageCount: 281,
  },
  {
    id: '4',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    cover: 'https://covers.openlibrary.org/b/id/8100936-L.jpg',
    description: 'A fantasy adventure of Bilbo Baggins in Middle-earth.',
    genre: ['Fantasy', 'Adventure'],
    publishYear: 1937,
    rating: 4.8,
    pageCount: 310,
  },
  {
    id: '5',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    cover: 'https://covers.openlibrary.org/b/id/8490493-L.jpg',
    description: 'A romantic novel of manners that critiques societal norms.',
    genre: ['Romance', 'Classic'],
    publishYear: 1813,
    rating: 4.5,
    pageCount: 279,
  },
  {
    id: '6',
    title: 'Brave New World',
    author: 'Aldous Huxley',
    cover: 'https://covers.openlibrary.org/b/id/7205017-L.jpg',
    description: 'A dystopian future dominated by technology and social engineering.',
    genre: ['Dystopian', 'Science Fiction'],
    publishYear: 1932,
    rating: 4.3,
    pageCount: 268,
  },
  {
    id: '7',
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    cover: 'https://covers.openlibrary.org/b/id/8225636-L.jpg',
    description: 'A story of teenage rebellion and alienation through Holden Caulfield’s eyes.',
    genre: ['Classic', 'Young Adult'],
    publishYear: 1951,
    rating: 4.0,
    pageCount: 214,
  },
  {
    id: '8',
    title: 'Moby Dick',
    author: 'Herman Melville',
    cover: 'https://covers.openlibrary.org/b/id/7222252-L.jpg',
    description: 'A whaling voyage that turns into a quest for vengeance.',
    genre: ['Classic', 'Adventure'],
    publishYear: 1851,
    rating: 3.8,
    pageCount: 585,
  },
  {
    id: '9',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    cover: 'https://covers.openlibrary.org/b/id/8369254-L.jpg',
    description: 'A philosophical story of a shepherd searching for treasure and meaning.',
    genre: ['Philosophy', 'Adventure'],
    publishYear: 1988,
    rating: 4.6,
    pageCount: 208,
  },
  {
    id: '10',
    title: 'Harry Potter and the Sorcerer’s Stone',
    author: 'J.K. Rowling',
    cover: 'https://covers.openlibrary.org/b/id/7888781-L.jpg',
    description: 'The magical beginning of Harry Potter’s adventures at Hogwarts.',
    genre: ['Fantasy', 'Young Adult'],
    publishYear: 1997,
    rating: 4.9,
    pageCount: 309,
  },
   // Add additional 45 entries
   ...Array.from({ length: 45 }, (_, index) => ({
    id: (6 + index).toString(),
    title: `Book Title ${6 + index}`,
    author: `Author ${6 + index}`,
    cover: `https://covers.openlibrary.org/b/id/${1000000 + index}-L.jpg`,
    description: `Description of Book Title ${6 + index}.`,
})),
  ];
  